linters:
  stylelint:
    config: 'stylelint.config.js'
files:
    ignore:
        - 'assets/img/*'
        - 'assets/js/*'
        - 'assets/css/reset.css' 
        - 'LICENSE'
        - '.gitignore'
        - 'README.md'
branches:    
    ignore:
        - 'master'        
fixers:
    enable: true